In [9]:
# Loss function --> Key to optimize our network

# 1. Categorical Cross Entropy ---> Generally used for classification

# Say I have the the following scenario where in the output values are [Red, Green , Blue], and we have the following batch of data:
import numpy as np 

outputs = [[0.7,0.1,0.2],
           [0.1,0.5,0.4],
           [0.02,0.9,0.08]]

true_labels = [[1,0,0],
               [0,1,0],
               [0,1,0]]

class CCE:
    def ce_loss(self,outputs,true_labels):
        l = - (true_labels * np.log(outputs))
        self.loss = np.sum(l,axis=1,keepdims=True)

ce = CCE()     

In [12]:
ce.ce_loss(outputs,true_labels)
ce.loss

array([[0.35667494],
       [0.69314718],
       [0.10536052]])

In [13]:
ce.loss.shape

(3, 1)

 NOTE: The base of the log is generally taken as 'e'. Even if we take another base it doesn't really matter since any base can be represented in terms of 'e' and base 2 basically turn out be the scaling factor. I only adavantage of using base 2 is that it is faster to comppute, but anyway CE is never the cotly part of NN for it not something to be overly concerend with.

In [15]:
# Fancy indexing in NumPy

softmax_outputs = np.array([
    [0.7, 0.1, 0.2],  # Row 0
    [0.1, 0.5, 0.4],  # Row 1
    [0.02, 0.9, 0.08] # Row 2
])

class_targets = [0, 1, 1]  # Target indices

print(softmax_outputs[[0,1,2],class_targets]) # [rows,columns]


[0.7 0.5 0.9]


In [17]:
loss = -np.log( softmax_outputs[[0,1,2],class_targets])
loss

array([0.35667494, 0.69314718, 0.10536052])

In [19]:
# Average loss

np.mean(loss)

0.38506088005216804