In [6]:
import numpy as np

inputs= np.array([[1, 2, 3, 2.5],[2., 5., -1.,2]])
print(inputs.shape)

(2, 4)


In [ ]:
# Practice

import numpy as np

exp_values = np.exp(inputs - np.max(inputs,axis=1, keepdims=True))
probabilites = exp_values / np.sum(exp_values,axis=1,keepdims=True)
print(probabilites)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


In [5]:
test = np.random.randn(2,4)
print(test.shape)

(2, 4)


In [11]:
# ReLU Acctivation Function

import numpy as np

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = np.maximum(0,inputs)
output.shape # Shape of (8,) means basically a shape of (1,8)

(8,)

In [22]:
class Activaton_ReLU:
    # Forward Pass
    def forward(self, inputs):
        # Calculate output values from input
        self.output = np.maximum(0, inputs)
        

In [23]:
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

X, y = spiral_data(samples=100, classes=3)
print(X.shape)
print(y.shape)

(300, 2)
(300,)


In [26]:
%run dense_layer.ipynb # This is the magic command to use the function from other juypter notebooks

(2, 3)


In [30]:
dense1 = Layer_Dense(2,3)
dense1.forward(X)
dense1.output[:5]

(2, 3)


array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 1.8302801e-04, -7.7334560e-05,  8.6269654e-05],
       [ 2.0213184e-04, -1.4989771e-04,  1.2648919e-04],
       [-2.4653360e-04, -1.2495469e-04, -5.3032099e-06],
       [-2.4447130e-04, -1.8850621e-04,  2.6007254e-05]], dtype=float32)

In [35]:
act = Activaton_ReLU()
act.forward(dense1.output)
print(act.output[:5])

[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.8302801e-04 0.0000000e+00 8.6269654e-05]
 [2.0213184e-04 0.0000000e+00 1.2648919e-04]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 2.6007254e-05]]


In [ ]:
class Softmax:
    
    def forward(self,inputs):
        norm = np.sum(np.exp(inputs),axis=1,keepdims=True)
        self.output = np.exp(inputs) / norm

In [ ]:
soft = Softmax()
soft.forward(dense1.output) 
print(soft.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.333373   0.33328623 0.33334076]
 [0.33338085 0.3332635  0.33335564]
 [0.33329302 0.33333355 0.33337343]
 [0.33329707 0.3333157  0.33338723]]


In [ ]:
import numpy as np
inputs = np.array([[1000, 1001, 1002]])
print(np.exp(inputs))  # This can cause an overflow error --> Therefore we subtract with the maximum value for numberical stability --> a^(n - m) = a^n/a^m


[[inf inf inf]]


C:\Users\loghi\AppData\Local\Temp\ipykernel_14808\3983015485.py:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(inputs))  # This can cause an overflow error


In [ ]:
# Better implementation of softmax:

class SoftMax:
    
    def forward(self,inputs):
        stable_exp = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        self.output = stable_exp / np.sum(stable_exp,axis=1,keepdims=True)

In [40]:
softM = SoftMax()
softM.forward(dense1.output) 
print(softM.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.333373   0.33328623 0.33334076]
 [0.33338085 0.3332635  0.33335564]
 [0.33329302 0.33333355 0.33337343]
 [0.33329707 0.3333157  0.33338723]]
