## Array Summation

In [9]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A.shape)
print(A)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.sum(A)) # or print(np.sum(A,axis=None))

45


In [10]:
print(np.sum(A,axis=0)) # Sum the rows / elements of the columns

[12 15 18]


In [ ]:
# keepdims will be useful when we deal with softmax later.

print(np.sum(A,axis=0,keepdims=True).shape)
print(np.sum(A,axis=0,keepdims=False).shape)

(1, 3)
(3,)


In [ ]:
print(np.sum(A,axis=1)) # Sum the columns / elements of the rows

[ 6 15 24]


In [17]:
print(np.sum(A,axis=1,keepdims=True).shape)
print(np.sum(A,axis=1,keepdims=False).shape) 

(3, 1)
(3,)


## Array Broadcasting

In [22]:
# Broadcasting rules in Python

B = np.array([[1,2,3],[4,5,6],[7,8,9]])
bias = np.array([[5],[9],[8]])
print(B.shape)
print(bias.shape)
print(B + bias)

(3, 3)
(3, 1)
[[ 6  7  8]
 [13 14 15]
 [15 16 17]]


Python extends the dimension to make sure the matrices can be added

In [26]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
bias1 = np.array([[1,2,3]])

print(C + bias1)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [34]:
# Practical example: Say from a matrix we want to subtract the maximum value from each row. 
# Expected answer : [[-2,-1,0],[-2,-1,0],[-2,-1,0]]

D = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.max(D,axis=1) # row wise remember

array([3, 6, 9])

In [37]:
D - np.max(D,axis=1,keepdims=True) # Make sure to keep the correct shape

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])